version: '3.3'

services:
  backend:
    # image: gcr.io/registryId/backend_dev
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    # - ./src:/backend/src
    ports:
      - 4000:4000
    env_file:
      - ./.env.dev
    command: 'npm run build && npm run start:prod'
    # logging:
    #   driver: gcplogs
    links:
      - postgres

  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432

networks:
  default:
    external:
      name: bev_networks
